---
driver:
  name: vagrant
  name: digitalocean

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: vagrant
  - name: digitalocean-ubuntu-12.04
    driver:
      name: digitalocean
      access_token: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>
      ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
      image: 10321777

suites:
  - name: default
    run_list:
      - recipe[chef-davical::default]
    attributes: {davical: {server_name: "ical.example.com", system_email: "admin@email.com", system_name: "Application" }}
